### ISSUE TITLE
Markdown formatting in the blog

### ISSUE THREAD

**Issue by IanLee1521** [herrBez/elastic-blog-openshift-logging#2]
In the actual blog, there are a few times where there are two API calls included in the same code block, which means that there is some massaging that needs to be done after copying.

I would recommend that these be broken out to separate code blocks to enable easy copying, and also enable the syntax highlighting of those blocks. Here is one example, but there are several: 

<img width="842" alt="image" src="https://github.com/herrBez/elastic-blog-openshift-logging/assets/828452/09e53ffc-1a5a-49ff-82c9-770c0ae96517">

**Comment by herrBez** [comment]
Hi thank you for the feedback. I am trying to work on all these initial feedbacks at once. I will keep you posted.
In the meantime I uploaded the file `BLOG.md` and `BLOG.md.j2` (so that the code snippets can be versioned separately from the blog-post itself).

**Comment by herrBez** [comment]
The new version of the blog should contain the fix ^^
